services:
  wledsound:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wledsound
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"      # Web Dashboard
      - "11988:11988/udp"    # WLED AudioSync
      - "4048:4048/udp"      # WLED DDP
    volumes:
      - ./config:/config
      - ./wledsound:/app/wledsound
    environment:
      - TZ=UTC
